apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: docker:19-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mounthPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
