apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: docker:19-dind
      imagePullPolicy: Always
      securityContext:
        privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
