apiVersion: v1
kind: Pod
metadata:
  label: cd-jenkins-jenkins-slave
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent
      imagePullPolicy: Always
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: docker
      image: docker:19-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mounthPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
