version: "3.1"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=sqlpass

  server:
    depends_on:
      - db
    build:
      context: ./server
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=sqlpass
      - PGDATABASE=postgres
      - PGPORT=5432
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    stdin_open: true
    build:
      context: ./client
    ports:
      - "8080:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./client:/app
