version: "3.1"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=sqlpass
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=sqlpass
      - PGDATABASE=postgres
      - PGPORT=5432
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./client:/app
