apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-west-1

managedNodeGroups:
  - name: group-1
    labels: {app: db}
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true
  - name: group-2
    labels: {app: web}
    instanceType: t2.micro
    desiredCapacity: 2
